### PR TITLE
Set `url.full` attribute on spans logged for HTTP requests

### PR DESCRIPTION
**Pull request by ahoppen**
We previously only set the request method on these spans, which made it hard to identify which exact HTTP request was causing this span to be emitted.

Also record the URL of the HTTP request to add more information to these spans. While at it, also record the request body size because we already had an attribute key configured for it.

### CODE REVIEW

File: Sources/AsyncHTTPClient/TracingSupport.swift [hunk 1]
```diff
@@ -23,6 +24,64 @@ import Tracing
...
+
+    static func handleRequestTracingAttributes(
+        _ span: Span,
+        _ request: HTTPClient.Request,
+        keys: HTTPClient.TracingConfiguration.AttributeKeys
+    ) {
+        handleRequestTracingAttributes(
+            span,
+            requestMethod: request.method.rawValue,
+            url: request.url.description,
```
Comment (FranzBusch) [inline Sources/AsyncHTTPClient/TracingSupport.swift]: I think we need to be careful with that. The full URL can include PII.

Comment (ahoppen) [reply Sources/AsyncHTTPClient/TracingSupport.swift]: Fair point. What do you think of the following: Only log only the host name by default. I wouldn’t consider that as PII and it might already give a hint as to what's being requested. We then add a configuration option to `TracingConfiguration` that allows users to opt into recording the entire URL in traces.

Comment (FranzBusch) [reply Sources/AsyncHTTPClient/TracingSupport.swift]: Yeah I think I would recommend doing this

1. Emit `server.address`, `server.port`, `url.scheme`, `HTTP method`, `status` by default.
2. Emit `url.path` by default but document that callers should configure redaction if they hit user-scoped paths.
3. Make `url.full` and `query` string opt-in.

**Comment by ahoppen** [comment]
Added the more scoped logging and configuration options to opt into full URL logging and to opt out to path logging. 

I chose to mark `DeconstructedURL` as `@usableFromInline` so that I can use it for the structured field tracing. Let me know if there’s an issue with that.

**Comment by czechboy0** [comment]
I think `url.full` should be enabled by default, following OpenTelemetry standard attributes: https://opentelemetry.io/docs/specs/semconv/registry/attributes/url/#url-full

Almost any string field can, in theory, have PII, and I think this is the wrong place to try to make that call. Let application owners filter PII in their telemetry backends instead.

**Comment by ahoppen** [comment]
> I think url.full should be enabled by default, following OpenTelemetry standard attributes

Are you suggesting that we don’t have any configuration options for this in async-http-client? I personally don’t have an opinion either way.

**Comment by czechboy0** [comment]
That's right. That's both how OpenTelemetry and the Swift observability libraries are designed.

**Comment by ahoppen** [comment]
Updated the PR to remove the configuration options.

**Comment by ktoso** [comment]
Just chiming in to say this looks good! Agree on not doing tens of settings in the lib itself, collectors can handle that 👍

**Review by ktoso — APPROVED** [review]

**Comment by ahoppen** [comment]
@czechboy0 @FranzBusch could I get another review on this?

File: Sources/AsyncHTTPClient/TracingSupport.swift [hunk 2]
```diff
@@ -19,10 +19,85 @@ import NIOHTTP1
...
+        configuration: HTTPClient.TracingConfiguration
+    ) {
+        let keys = configuration.attributeKeys
+        span.attributes[keys.requestMethod] = requestMethod
+        span.attributes[keys.urlScheme] = deconstructedURL?.scheme.rawValue
+        span.attributes[keys.serverAddress] = deconstructedURL?.connectionTarget.host
+        span.attributes[keys.serverPort] = deconstructedURL?.connectionTarget.port
+        span.attributes[keys.requestBodySize] = requestBodySize
+        span.attributes[keys.urlPath] = url?.path
+        span.attributes[keys.fullUrl] = url?.absoluteString
```
Comment (glbrntt) [inline Sources/AsyncHTTPClient/TracingSupport.swift]: Can you strip the username and password from the URL if they're present (per https://opentelemetry.io/docs/specs/semconv/url/#sensitive-information)?

**Review by glbrntt — CHANGES_REQUESTED** [review]

File: Sources/AsyncHTTPClient/TracingSupport.swift (hunk 2 above)
Comment (ahoppen) [reply Sources/AsyncHTTPClient/TracingSupport.swift]: I’ll make the changes once we’ve converged on what should and what should not be included in the logs.

File: Sources/AsyncHTTPClient/TracingSupport.swift (hunk 1 above)
Comment (ahoppen) [reply Sources/AsyncHTTPClient/TracingSupport.swift]: Syned offline and agreed that we should only strip username + password, log everything else as @glbrntt suggested. We don’t need to strip query parameters because https://opentelemetry.io/docs/specs/semconv/url/#sensitive-information says

> Instrumentations *that are aware of specific sensitive query string* […]

Since async-http-client is not aware of sensitive query strings, we don’t have to scrub it.

**Comment by ahoppen** [comment]
Updated to only strip username and password. I would appreciate another review.

**Review by ktoso — APPROVED** [review]
Looks good to me, we do our best but it’s collectors and vis config that may need to do more scrubbing anyway.

**Review by glbrntt — APPROVED** [review]
LGTM. I think the docs failure will be resolved by https://github.com/swift-server/async-http-client/pull/913

**Comment by ahoppen** [comment]
If you’re happy with this, could you merge the PR? I don’t have merge access to this repo.

**Comment by glbrntt** [comment]
I'm going to wait for the other PR to be merged first as the failure was introduced by your code and we'd rather not merge new CI regressions.

**Comment by glbrntt** [comment]
Agh, sorry @ahoppen -- I was wrong, that change didn't fix it. It's not obvious to me why your change fails to build for docs but does for "regular" CI runs.

```
/__w/async-http-client/async-http-client/Sources/AsyncHTTPClient/TracingSupport.swift:40:13: error: switch must be exhaustive
 38 |     ) {
 39 |         let requestBodySize: Int? =
 40 |             switch request.body?.mode {
    |             |- error: switch must be exhaustive
    |             `- note: add missing case: '.some(.httpClientRequestBody(length: let length, startUpload: let startUpload))'
 41 |             case .asyncSequence(.known(let length), _), .sequence(.known(let length), _, _):
 42 |                 Int(length)
```

**Comment by ahoppen** [comment]
Oh, interesting that this got caught as part of the doc check. I just didn’t check that code builds with `UnstableHTTPAPIsSupport` enabled. Should be fixed now.
